### ISSUE TITLE
Plugin deprecation

### ISSUE THREAD

**Issue by skonefal** [intelsdi-x/snap-plugin-processor-tag#13]
Shouldn't this plugin be deprecated? Framework itself support tagging, right?

**Comment by sandlbn** [comment]
@skonefal I'm planning to add more features to this plugin, like external source of tag. Which will allow change tags on the fly.

**Comment by skonefal** [comment]
Sounds interesting. I imagine that there might be some use cases for dynamic tags, e.g. when you really need to change them and you cannot afford stopping the whole workflow.

From the other hand, this configuration would probably be harder to maintain in Tribe. And for the record, we are orchestrating our workflows from code and we are restarting whole workflows with new tags, when metric domain changes (sometimes as often as every tens of seconds) - but we are OK that metrics will not flow for sec or two during restart :)

**Comment by uwe42** [comment]
Hi,
we need this pugin, tribe is not an option due to rapid change of infrastructure (PBS_torque). And can not predict where jobs will run. We use this to track jobs in a changing environment.
